IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('BIZDATADEFITEM_PERIODVERSION') AND O.NAME = 'FK_BIZDATAD_REFERENCE_BIZDATA')
ALTER TABLE BIZDATADEFITEM_PERIODVERSION
   DROP CONSTRAINT FK_BIZDATAD_REFERENCE_BIZDATA
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('BIZDATADEFITEM_PERIODVERSION') AND O.NAME = 'FK_BIZDATAD_REFERENCE_BIZDATAD')
ALTER TABLE BIZDATADEFITEM_PERIODVERSION
   DROP CONSTRAINT FK_BIZDATAD_REFERENCE_BIZDATAD
go

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('BIZDATADEFITEM_PERIODVERSION')
            AND   NAME  = 'IDX_BIZDEFITEM_PERIODVERSION_DATAID'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX BIZDATADEFITEM_PERIODVERSION.IDX_BIZDEFITEM_PERIODVERSION_DATAID
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('BIZDATADEFITEM_PERIODVERSION')
            AND   TYPE = 'U')
   DROP TABLE BIZDATADEFITEM_PERIODVERSION
go

/*==============================================================*/
/* Table: BIZDATADEFITEM_PERIODVERSION                          */
/*==============================================================*/
CREATE TABLE BIZDATADEFITEM_PERIODVERSION (
   ID                   NUMERIC(18)          NOT NULL,
   ITEMBIZDATAID        NUMERIC(18)          NOT NULL,
   PERIOD_INTERVAL      NUMERIC(18)          NULL,
   CONSTRAINT PK_BIZDATADEFITEM_PERIODVERSIO PRIMARY KEY (ID)
)
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'M-N版本预测数据',
   'user', @CURRENTUSER, 'table', 'BIZDATADEFITEM_PERIODVERSION'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '定义项业务数据ID',
   'user', @CURRENTUSER, 'table', 'BIZDATADEFITEM_PERIODVERSION', 'column', 'ITEMBIZDATAID'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '期间间隔',
   'user', @CURRENTUSER, 'table', 'BIZDATADEFITEM_PERIODVERSION', 'column', 'PERIOD_INTERVAL'
go


ALTER TABLE BIZDATADEFITEM_PERIODVERSION
   ADD CONSTRAINT FK_BIZDATAD_REFERENCE_BIZDATA FOREIGN KEY (ITEMBIZDATAID)
      REFERENCES BIZDATA (ID)
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('BIZDATADEFITEM_PERIODVERSION') AND O.NAME = 'FK_BIZDATAD_REFERENCE_BIZDATAD')
ALTER TABLE BIZDATADEFITEM_PERIODVERSION
   DROP CONSTRAINT FK_BIZDATAD_REFERENCE_BIZDATAD
go

ALTER TABLE BIZDATADEFITEM_PERIODVERSION
   ADD CONSTRAINT FK_BIZDATAD_REFERENCE_BIZDATAD FOREIGN KEY (ID)
      REFERENCES BIZDATADEFITEM (ID)
         ON DELETE CASCADE
go


--M-N版本预测
insert into SYSDICTIONARYITEM ( VERSION, CLASSNAME, ATTRIBUTENAME, VALUE, VALUEDESC)
values  ( 0, 'BIZDATA', 'TYPE', 44, 'BIZDATA_TYPE_PERIODVERSION'); 

insert into funpermission ( VERSION, TYPE, CODE, NAME, DESCRIPTION, COMMENTS) values ( 0, '0', 'PERIOD VERSION', 'M-N版本预测', 'bizdata_periodVersion', '业务数据管理'); 


insert into OPERATORUSER_FUNPERMISSION
  ( VERSION, OPERATORUSERID, FUNPERMISSIONID)
values ( 0,
   (select ID from OPERATORUSER where LOGINNAME = 'dmadmin'),
   (select ID from FUNPERMISSION where DESCRIPTION = 'bizdata_periodVersion'));
   

