/**
 * 
 */
package dmdd.dmddjava.common.constant;

/**
 * @author liuzhen
 *
 */
public class ExceptionConst
{

	/**
	 * 
	 */
	public ExceptionConst()
	{
		// TODO Auto-generated constructor stub
	}
	
	public final static String EXCEPTION_CAUSECODE_SYSTEMSTATUS_EXCEPTION_ROLLINGPERIOD = "EXCEPTION_CAUSECODE_SYSTEMSTATUS_EXCEPTION_ROLLINGPERIOD";	// 期间滚动异常，不提供服务
	public final static String EXCEPTION_CAUSECODE_SYSTEMSTATUS_ROLLINGPERIOD = "EXCEPTION_CAUSECODE_SYSTEMSTATUS_ROLLINGPERIOD";	// 期间滚动中，不提供服务
	public final static String EXCEPTION_CAUSECODE_SYSTEMSTATUS_EXCEPTION_RUNNINGFORECAST = "EXCEPTION_CAUSECODE_SYSTEMSTATUS_EXCEPTION_RUNNINGFORECAST";	// 预测运行异常，不提供服务
	public final static String EXCEPTION_CAUSECODE_SYSTEMSTATUS_RUNNINGFORECAST = "EXCEPTION_CAUSECODE_SYSTEMSTATUS_RUNNINGFORECAST";	// 预测运行中，不提供服务
	
	public final static String EXCEPTION_CAUSECODE_USER_LICENSENUM = "EXCEPTION_CAUSECODE_USER_LICENSENUM";		// 用户数已达购买许可数
	public final static String EXCEPTION_CAUSECODE_USER_CONLOGON = "EXCEPTION_CAUSECODE_USER_CONLOGON";		// 用户已在其他位置登陆
	
	
	public final static String EXCEPTION_CAUSECODE_ORGANIZATIONCHARACTERLAYER_MAXLAYER = "EXCEPTION_CAUSECODE_ORGANIZATIONCHARACTERLAYER_MAXLAYER";		// 组织特征层次不够
	public final static String EXCEPTION_CAUSECODE_ORGANIZATIONLAYER_MAXLAYER = "EXCEPTION_CAUSECODE_ORGANIZATIONLAYER_MAXLAYER";		// 组织层次不够
	public final static String EXCEPTION_CAUSECODE_ORGANIZATIONCHARACTER_DELETEERROR = "EXCEPTION_CAUSECODE_ORGANIZATIONCHARACTER_DELETEERROR";//组织特征已经关联了组织，不能删除
	public final static String EXCEPTION_CAUSECODE_ORGANIZATIONORGCHARACTER_SAMECHARACTERTYPE ="EXCEPTION_CAUSECODE_ORGANIZATIONORGCHARACTER_SAMECHARACTERTYPE";//该组织的特征列表中已有该类别的特征
	
	public final static String EXCEPTION_CAUSECODE_PRODUCTCHARACTERLAYER_MAXLAYER = "EXCEPTION_CAUSECODE_PRODUCTCHARACTERLAYER_MAXLAYER";		// 产品特征层次不够
	public final static String EXCEPTION_CAUSECODE_PRODUCTLAYER_MAXLAYER = "EXCEPTION_CAUSECODE_PRODUCTLAYER_MAXLAYER";		// 产品层次不够
	public final static String EXCEPTION_CAUSECODE_PRODUCTCHARACTER_DELETEERROR = "EXCEPTION_CAUSECODE_PRODUCTCHARACTER_DELETEERROR";		// 产品特征已经关联了产品，不能删除
	public final static String EXCEPTION_CAUSECODE_PRODUCTPROCHARACTER_SAMECHARACTERTYPE = "EXCEPTION_CAUSECODE_PRODUCTPROCHARACTER_SAMECHARACTERTYPE";//该产品的特征列表中已有该类别的特征
	
	/**本地编制期间与服务器不一致*/
	public final static String EXCEPTION_CAUSECODE_COMPILEPERIOD_UNMATCH = "EXCEPTION_CAUSECODE_COMPILEPERIOD_UNMATCH";
	/**期间滚动任务已经被创建*/
	public final static String EXCEPTION_CAUSECODE_PERIODROLLTASK_CREATED = "EXCEPTION_CAUSECODE_PERIODROLLTASK_CREATED";
	/**预测类别与其他预测类别当期预测范围有重叠*/
	public final static String EXCEPTION_CAUSECODE_FORECASTINSTPROORG_OVERLAP = "EXCEPTION_CAUSECODE_FORECASTINSTPROORG_OVERLAP";
	/**预测类别与其他预测类别下期预测范围有重叠*/
	public final static String EXCEPTION_CAUSECODE_FORECASTINSTNEXTPROORG_OVERLAP = "EXCEPTION_CAUSECODE_FORECASTINSTNEXTPROORG_OVERLAP";
	
	public final static String EXCEPTION_CAUSECODE_FCCOMB_ASFCFINAL = "EXCEPTION_CAUSECODE_FCCOMB_ASFCFINAL";	// 组合预测目前作为最终预测，不可修改定义内容
	
	public final static String EXCEPTION_CAUSECODE_HISTORYDATA_ADJUSTUNEXIST ="EXCEPTION_CAUSECODE_HISTORYDATA_ADJUSTUNEXIST";	// 对不存在的历史数据值进行调整
	
	
	
	public final static String EXCEPTION_CAUSECODE_OBJECT_NOT_IN_DATABASE = "EXCEPTION_CAUSECODE_OBJECT_NOT_IN_DATABASE";		// 该对象在数据库中不存在
	
	public final static String EXCEPTION_CAUSECODE_PARENTNODE_HAS_BEEN_MODIFIED="EXCEPTION_CAUSECODE_PARENTNODE_HAS_BEEN_MODIFIED";//上级节点被其他人改动过，请重新查询后再修改
	
	/**
	 * 数据已经被其他线程修改，请重新获取最新数据
	 */
	public final static String EXCEPTION_CAUSECODE_DATA_HAS_BEEN_MODIFIED="EXCEPTION_CAUSECODE_DATA_HAS_BEEN_MODIFIED";
	
	public final static String EXCEPTION_CAUSECODE_OUT_OF_DESIGN="EXCEPTION_CAUSECODE_OUT_OF_DESIGN";//超出设计
	
	
	
	public final static String EXCEPTION_CAUSECODE_OLD_PASSWORD_NOT_CORRECT="EXCEPTION_CAUSECODE_OLD_PASSWORD_NOT_CORRECT";//旧密码错误
	
	public final static String EXCEPTION_CAUSECODE_NO_RECORD_IN_SYSPERIOD="EXCEPTION_CAUSECODE_NO_RECORD_IN_SYSPERIOD";//在表中查不到记录
	
	public final static String EXCEPTION_CAUSECODE_NO_PERIODROLLTASK_FORECASTINST_IN_DATABASE="EXCEPTION_CAUSECODE_NO_PERIODROLLTASK_FORECASTINST_IN_DATABASE";//在数据库中找不到_periodRollTask_ForecastInst
	
	public final static String EXCEPTION_CAUSECODE_ILLEGAL_START="EXCEPTION_CAUSECODE_ILLEGAL_START";//非法启动系统，请使用正版
	
	//20110314 增加了价格数据关联删除时报错解析begin
	public final static String EXCEPTION_CAUSECODE_PRICEDATA_FK_OID="PRICEDATA_FK_OID";//已经有价格关联，不能删除
	//20110314 增加了价格数据关联删除时报错解析end.
	
	public final static String EXCEPTION_CAUSECODE_BREAKDOWNRULE_UK_N_C_T="BREAKDOWNRULE_UK_N_C_T";//分解规则名称，编码，类型必须唯一
	/**
	 * @param args
	 */
	public static void main( String[] args )
	{
		// TODO Auto-generated method stub

	}

}
