IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('BIZDATADEFITEM_ADDFC') AND O.NAME = 'FK_BIZDATAD_BDADDFC_B_BIZDATA')
ALTER TABLE BIZDATADEFITEM_ADDFC
   DROP CONSTRAINT FK_BIZDATAD_BDADDFC_B_BIZDATA
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('BIZDATADEFITEM_ADDFC') AND O.NAME = 'FK_BIZDATAD_BDADDFC_I_BIZDATAD')
ALTER TABLE BIZDATADEFITEM_ADDFC
   DROP CONSTRAINT FK_BIZDATAD_BDADDFC_I_BIZDATAD
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('BIZDATADEFITEM_ADDFC')
            AND   TYPE = 'U')
   DROP TABLE BIZDATADEFITEM_ADDFC
go

/*==============================================================*/
/* Table: BIZDATADEFITEM_ADDFC                                  */
/*==============================================================*/
CREATE TABLE BIZDATADEFITEM_ADDFC (
   ID                   NUMERIC(18)          NOT NULL,
   ITEMBIZDATAID        NUMERIC(18)          NOT NULL,
   CONSTRAINT PK_BIZDATADEFITEM_ADDFC PRIMARY KEY (ID)
)
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '期间累计',
   'user', @CURRENTUSER, 'table', 'BIZDATADEFITEM_ADDFC'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '定义项业务数据ID',
   'user', @CURRENTUSER, 'table', 'BIZDATADEFITEM_ADDFC', 'column', 'ITEMBIZDATAID'
go

ALTER TABLE BIZDATADEFITEM_ADDFC
   ADD CONSTRAINT FK_BIZDATAD_BDADDFC_B_BIZDATA FOREIGN KEY (ITEMBIZDATAID)
      REFERENCES BIZDATA (ID)
go

ALTER TABLE BIZDATADEFITEM_ADDFC
   ADD CONSTRAINT FK_BIZDATAD_BDADDFC_I_BIZDATAD FOREIGN KEY (ID)
      REFERENCES BIZDATADEFITEM (ID)
         ON DELETE CASCADE
go


IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('BIZDATADEFITEM_AVGHIS') AND O.NAME = 'FK_BIZDATAD_BDAVGHIS__BIZDATA')
ALTER TABLE BIZDATADEFITEM_AVGHIS
   DROP CONSTRAINT FK_BIZDATAD_BDAVGHIS__BIZDATA
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('BIZDATADEFITEM_AVGHIS') AND O.NAME = 'FK_BIZDATAD_BDAVGHIS__BIZDATAD')
ALTER TABLE BIZDATADEFITEM_AVGHIS
   DROP CONSTRAINT FK_BIZDATAD_BDAVGHIS__BIZDATAD
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('BIZDATADEFITEM_AVGHIS')
            AND   TYPE = 'U')
   DROP TABLE BIZDATADEFITEM_AVGHIS
go

/*==============================================================*/
/* Table: BIZDATADEFITEM_AVGHIS                                 */
/*==============================================================*/
CREATE TABLE BIZDATADEFITEM_AVGHIS (
   ID                   NUMERIC(18)          NOT NULL,
   ITEMBIZDATAID        NUMERIC(18)          NOT NULL,
   PERIODNUM            NUMERIC(18)          NULL,
   CONSTRAINT PK_BIZDATADEFITEM_AVGHIS PRIMARY KEY (ID)
)
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '期间历史平均',
   'user', @CURRENTUSER, 'table', 'BIZDATADEFITEM_AVGHIS'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '定义项业务数据ID',
   'user', @CURRENTUSER, 'table', 'BIZDATADEFITEM_AVGHIS', 'column', 'ITEMBIZDATAID'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '期间数',
   'user', @CURRENTUSER, 'table', 'BIZDATADEFITEM_AVGHIS', 'column', 'PERIODNUM'
go

ALTER TABLE BIZDATADEFITEM_AVGHIS
   ADD CONSTRAINT FK_BIZDATAD_BDAVGHIS__BIZDATA FOREIGN KEY (ITEMBIZDATAID)
      REFERENCES BIZDATA (ID)
go

ALTER TABLE BIZDATADEFITEM_AVGHIS
   ADD CONSTRAINT FK_BIZDATAD_BDAVGHIS__BIZDATAD FOREIGN KEY (ID)
      REFERENCES BIZDATADEFITEM (ID)
         ON DELETE CASCADE
go


IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('BIZDATADEFITEM_ADDHIS') AND O.NAME = 'FK_BIZDATAD_BDADDHIS__BIZDATA')
ALTER TABLE BIZDATADEFITEM_ADDHIS
   DROP CONSTRAINT FK_BIZDATAD_BDADDHIS__BIZDATA
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('BIZDATADEFITEM_ADDHIS') AND O.NAME = 'FK_BIZDATAD_BDADDHIS__BIZDATAD')
ALTER TABLE BIZDATADEFITEM_ADDHIS
   DROP CONSTRAINT FK_BIZDATAD_BDADDHIS__BIZDATAD
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('BIZDATADEFITEM_ADDHIS')
            AND   TYPE = 'U')
   DROP TABLE BIZDATADEFITEM_ADDHIS
go

/*==============================================================*/
/* Table: BIZDATADEFITEM_ADDHIS                                 */
/*==============================================================*/
CREATE TABLE BIZDATADEFITEM_ADDHIS (
   ID                   NUMERIC(18)          NOT NULL,
   ITEMBIZDATAID        NUMERIC(18)          NOT NULL,
   CONSTRAINT PK_BIZDATADEFITEM_ADDHIS PRIMARY KEY (ID)
)
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '期间累计',
   'user', @CURRENTUSER, 'table', 'BIZDATADEFITEM_ADDHIS'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '定义项业务数据ID',
   'user', @CURRENTUSER, 'table', 'BIZDATADEFITEM_ADDHIS', 'column', 'ITEMBIZDATAID'
go

ALTER TABLE BIZDATADEFITEM_ADDHIS
   ADD CONSTRAINT FK_BIZDATAD_BDADDHIS__BIZDATA FOREIGN KEY (ITEMBIZDATAID)
      REFERENCES BIZDATA (ID)
go

ALTER TABLE BIZDATADEFITEM_ADDHIS
   ADD CONSTRAINT FK_BIZDATAD_BDADDHIS__BIZDATAD FOREIGN KEY (ID)
      REFERENCES BIZDATADEFITEM (ID)
         ON DELETE CASCADE
go


